### ISSUE TITLE
some problem in auto-refine

### ISSUE THREAD

**Issue by HNUWangpx** [3dem/relion#1058]
I encountered some issues while running Relion step by step in the "relion30_tutorial_data" dataset, although everything was working fine before "Running the auto-refine job."
I also encountered the same issues when attempting to follow the steps in the "relion40_tutorial_precalculated_results" dataset.
The error occurred after the process had been running for a while, and I suspect it may match the description of the second possibility in the error message.

environment:
	RELION version: 4.0.1-commit-db9717
	Precision: BASE=double

	NVIDIA (R) Cuda compiler driver
	Copyright (c) 2005-2022 NVIDIA Corporation
	Built on Wed_Sep_21_10:33:58_PDT_2022
	Cuda compilation tools, release 11.8, V11.8.89
	Build cuda_11.8.r11.8/compiler.31833905_0

	Linux version 5.4.0-150-generic (buildd@bos03-amd64-012) 
	(gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)) 

the 'run.err' is follow:

ERROR: out of memory in /home/user/software/relion/src/acc/cuda/custom_allocator.cuh at line 435 (error-code 2)
in: /home/user/software/relion/src/acc/cuda/cuda_settings.h, line 65
ERROR:

A GPU-function failed to execute.

 If this occured at the start of a run, you might have GPUs which
are incompatible with either the data or your installation of relion.
If you

        -> INSTALLED RELION YOURSELF: if you e.g. specified -DCUDA_ARCH=50
           and are trying ot run on a compute 3.5 GPU (-DCUDA_ARCH=3.5),
           this may happen.

        -> HAVE MULTIPLE GPUS OF DIFFERNT VERSIONS: relion needs GPUS with
           at least compute 3.5. You may be trying to use a GPU older than
           this. If you have multiple generations, try specifying --gpu <X>
           with X=0. Then try X=1 in a new run, and so on. The numbering of
           GPUs may not be obvious from the driver or intuition. For a list
           of GPU compute generations, see

           en.wikipedia.org/wiki/CUDA#Version_features_and_specifications

        -> ARE USING DOUBLE-PRECISION GPU CODE: relion was been written so
           as to not require this, and may thus have unforeseen requirements
           when run in this mode. If you think it is nonetheless necessary,
           please consult the developers with this error.

If this occurred at the middle or end of a run, it might be that

        -> YOUR DATA OR PARAMETERS WERE UNEXPECTED: execution on GPUs is
           subject to many restrictions, and relion is written to work within
           common restraints. If you have exotic data or settings, unexpected
           configurations may occur. See also above point regarding
           double precision.
If none of the above applies, please report the error to the relion
developers at    github.com/3dem/relion/issues

=== Backtrace  ===
/home/user/software/relion/build/bin/relion_refine_mpi(_ZN11RelionErrorC2ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES7_l+0x77) [0x561c98fb14a7]
/home/user/software/relion/build/bin/relion_refine_mpi(+0x283033) [0x561c991e8033]
/home/user/software/relion/build/bin/relion_refine_mpi(_ZN14MlDeviceBundle24setupTunableSizedObjectsEm+0x634) [0x561c991eaa54]
/home/user/software/relion/build/bin/relion_refine_mpi(_ZN14MlOptimiserMpi11expectationEv+0x2b66) [0x561c98fd2776]
/home/user/software/relion/build/bin/relion_refine_mpi(_ZN14MlOptimiserMpi7iterateEv+0x109) [0x561c98fe12d9]
/home/user/software/relion/build/bin/relion_refine_mpi(main+0x67) [0x561c98f9cd27]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xe7) [0x7f5ca3322c87]
/home/user/software/relion/build/bin/relion_refine_mpi(_start+0x2a) [0x561c98f9fd3a]
==================
ERROR:

A GPU-function failed to execute.

 If this occured at the start of a run, you might have GPUs which
are incompatible with either the data or your installation of relion.
If you

        -> INSTALLED RELION YOURSELF: if you e.g. specified -DCUDA_ARCH=50
           and are trying ot run on a compute 3.5 GPU (-DCUDA_ARCH=3.5),
           this may happen.

        -> HAVE MULTIPLE GPUS OF DIFFERNT VERSIONS: relion needs GPUS with
           at least compute 3.5. You may be trying to use a GPU older than
           this. If you have multiple generations, try specifying --gpu <X>
           with X=0. Then try X=1 in a new run, and so on. The numbering of
           GPUs may not be obvious from the driver or intuition. For a list
           of GPU compute generations, see

           en.wikipedia.org/wiki/CUDA#Version_features_and_specifications

        -> ARE USING DOUBLE-PRECISION GPU CODE: relion was been written so
           as to not require this, and may thus have unforeseen requirements
           when run in this mode. If you think it is nonetheless necessary,
           please consult the developers with this error.

If this occurred at the middle or end of a run, it might be that

        -> YOUR DATA OR PARAMETERS WERE UNEXPECTED: execution on GPUs is
           subject to many restrictions, and relion is written to work within
           common restraints. If you have exotic data or settings, unexpected
           configurations may occur. See also above point regarding
           double precision.
If none of the above applies, please report the error to the relion
developers at    github.com/3dem/relion/issues

--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 4 in communicator MPI_COMM_WORLD
  Proc: [[20790,1],4]
  Errorcode: 1

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------

Thank you very much for your help.
[run.zip](https://github.com/3dem/relion/files/13764905/run.zip)

**Comment by biochem-fan** [comment]
This is probably the same issue as https://github.com/3dem/relion/issues/1056.

**Comment by HNUWangpx** [comment]
I will try to solve it according to it, and then provide feedback here. Thank you.

**Comment by HNUWangpx** [comment]
Excuse me, it seems that the problem has not been solved in issue #1056.

**Comment by biochem-fan** [comment]
Yes, it is not solved but please use that thread for further communication.

**Comment by HNUWangpx** [comment]
Okay, thank you for your help.
