### ISSUE TITLE
Relion-5.0 Class3D on subtomograms

### ISSUE THREAD

**Issue by pherepanov** [3dem/relion#1061]
I encountered several frustraiting issues when attempting 3D classification of subtomograms in Relion-5.0

1) when subtomograms are created in old style (i.e. with "2D stacks" option set to "NO"): 3D classification invariably fails with GPU memory errors:  

**ERROR: CudaCustomAllocator out of memory
 [requestedSpace:             3420000 B]
 [largestContinuousFreeSpace: 3359232 B]
 [totalFreeSpace:             6432256 B]**

This happens whether initional model is provided or not. GPU memory should be NOT an issue at all, since particles are only 36^3 pixels, and I have only 5-10k of them. The corresponding data.star files have all low _rlnNrOfSignificantSamples values (all well undr 2000), and  limiting --maxsig at 2000 or 500 does not help; reducing number of threads to 1 does not help either. The job fails with the same error at a random iteration (sometimes in the very beginning (iteration 1), and sometimes at iteration 7 or anywhere in between). This happens just when interesting averages start to appear (so frustraiting!). Submitting a Continue on such failed job produced an immediate crash with exact same error. It seems that Relion just asks for just a little bit more space than is available as "continuous space" on GPU. 

2) when subtomograms are generated as 2D stacks, and 3D classification is started without initial model ("None" in the intial model field): 3D classification does not fail with an error, but goes on without generating 3D volumes. Instead, classes.mrcs files are produced, which are stacks of 2D images (such stack is made of the same number of 2D images as the number of 3D classes requested in the classification job). Is this an expected behaviour, and what should we do with these classes? I have to add they do not look very noisy and not informative at all. 

3) when subtomograms are generated as 2D stacks, and 3D classification is started from an initial 3D model: the jobs fails just as in case #1 above with the GPU memory errors. 

**Environment:**
 - OS: Linux 3.10.0-1160.62.1.el7.x86_64 x86_64
 - MPI runtime: mpirun (Open MPI) 1.10.3
 - RELION version 5.0-beta-0-commit-cff855
 - GPU: Tesla V100-SXM2-32GB 

**Dataset:**
 - Box size: 36 px (cropped from 72)
 - Pixel size:  6.96 Å/px
 - Number of particles: 5,000 - 10,000 
 - Description: ~500 kDa protein

**Job options:**
 - Type of job: Class3D
 - Number of MPI processes: 5
 - Number of threads: 1-4
 - Full command (see `note.txt` in the job directory):
   ```
  `which relion_refine_mpi` --o Class3D/job187/run --i PseudoSubtomo/job157/particles.star --tomograms ReconstructTomograms/job055/tomograms.star --ref hxb2_refine_job300_run_class001.mrc --firstiter_cc --ini_high 60 --dont_combine_weights_via_disc --scratch_dir $TMPDIR --pool 3 --pad 2  --ctf --iter 35 --tau2_fudge 4 --particle_diameter 240 --K 5 --flatten_solvent --zero_mask --oversampling 1 --healpix_order 2 --offset_range 5 --offset_step 2 --sym C1 --norm --scale  --j 1 --gpu ""  --sigma_tilt 20 --sigma_psi 20 --pipeline_control Class3D/job187/
   ```

**Error message:**

....
 Expectation iteration 7 of 35
  35/  35 sec ............................................................~~(,_,">
 Maximization...
   0/   0 sec ............................................................~~(,_,">
ERROR: CudaCustomAllocator out of memory
 [requestedSpace:             3420000 B]
 [largestContinuousFreeSpace: 3359232 B]
 [totalFreeSpace:             6432256 B]
[3359232B] (3068928B) [3073024B] = 9501184B
ERROR: CudaCustomAllocator out of memory
 [requestedSpace:             3420000 B]
 [largestContinuousFreeSpace: 3359232 B]
 [totalFreeSpace:             6432256 B]
[3359232B] (3068928B) [3073024B] = 9501184B
ERROR: CudaCustomAllocator out of memory
 [requestedSpace:             3420000 B]
 [largestContinuousFreeSpace: 3359232 B]
 [totalFreeSpace:             6432256 B]
[3359232B] (3068928B) [3073024B] = 9501184B
ERROR: CudaCustomAllocator out of memory
 [requestedSpace:             3420000 B]
 [largestContinuousFreeSpace: 3359232 B]
 [totalFreeSpace:             6432256 B]
[3359232B] (3068928B) [3073024B] = 9501184B

**in: /camp/apps/misc/stp/sbstp/relion-5.0/src/acc/cuda/custom_allocator.cuh, line 539
ERROR: 

You ran out of memory on the GPU(s).

Each MPI-rank running on a GPU increases the use of GPU-memory. Relion
tries to distribute load over multiple GPUs to increase performance,
but doing this in a general and memory-efficient way is difficult.

1. Check the device-mapping presented at the beginning of each run,
   and be particularly wary of 'device X is split between N followers', which 
   will result in a higher memory cost on GPU X. In classifications, GPU-
   sharing between MPI-ranks is typically fine, whereas it will usually 
   cause out-of-memory during the last iteration of high-resolution refinement.

2. If you are not GPU-sharing across MPI-follower ranks, then you might be using a
   too-big box-size for the GPU memory. Currently, N-pixel particle images
   will require *roughly* 

		    (1.1e-8)*(N*2)^3  GB  

   of memory (per rank) during the final iteration of refinement (using
   single-precision GPU code, which is default). 450-pixel images can therefore
   just about fit into a GPU with 8GB of memory, since 11*(450*2)^3 ~= 8.02
   During classifications, resolution is typically lower and N is suitably
   reduced, which means that memory use is much lower.

3. If the above estimation fits onto (all of) your GPU(s), you may have 
   a very large number of orientations which are found as possible during
   the expectation step, which results in large arrays being needed on the 
   GPU. If this is the case, you should find large (>10'000) values of 
   '_rlnNrOfSignificantSamples' in your _data.star output files. You can try
   adding the --maxsig <P>, flag, where P is an integer limit, but you 
   should probably also consult expertise or re-evaluate your data and/or 
   input reference. Seeing large such values means relion is finding nothing
   to align.
If none of the above applies, please report the error to the relion
developers at github.com/3dem/relion/issues.

[gpu005:137014] *** Process received signal ***
[gpu005:137014] Signal: Segmentation fault (11)
[gpu005:137014] Signal code: Address not mapped (1)
[gpu005:137014] Failing at address: 0x28
[gpu005:137014] [ 0] /lib64/libpthread.so.0(+0xf630)[0x7ff0f3caa630]
[gpu005:137014] [ 1] /camp/apps/misc/stp/sbstp/5.0beta-tomo-GPU/bin/relion_refine_mpi(_ZN6AccPtrI8tComplexIdEE9freeIfSetEv+0x48)[0x4bb998]
[gpu005:137014] [ 2] /camp/apps/misc/stp/sbstp/5.0beta-tomo-GPU/bin/relion_refine_mpi(_ZN9Projector26computeFourierTransformMapER13MultidimArrayIdES2_iibbiPKS1_b+0x333e)[0x4ba3ce]
[gpu005:137014] [ 3] /camp/apps/misc/stp/sbstp/5.0beta-tomo-GPU/bin/relion_refine_mpi(_ZN7MlModel23setFourierTransformMapsEbidPK13MultidimArrayIdE+0x8e1)[0x6275a1]
[gpu005:137014] [ 4] /camp/apps/misc/stp/sbstp/5.0beta-tomo-GPU/bin/relion_refine_mpi(_ZN11MlOptimiser16expectationSetupEv+0x5a)[0x64591a]
[gpu005:137014] [ 5] /camp/apps/misc/stp/sbstp/5.0beta-tomo-GPU/bin/relion_refine_mpi(_ZN14MlOptimiserMpi11expectationEv+0x2fb)[0x47fdeb]
[gpu005:137014] [ 6] /camp/apps/misc/stp/sbstp/5.0beta-tomo-GPU/bin/relion_refine_mpi(_ZN14MlOptimiserMpi7iterateEv+0x105)[0x491d25]
[gpu005:137014] [ 7] /camp/apps/misc/stp/sbstp/5.0beta-tomo-GPU/bin/relion_refine_mpi(main+0x54)[0x44b014]
[gpu005:137014] [ 8] /lib64/libc.so.6(__libc_start_main+0xf5)[0x7ff0f31a6555]
[gpu005:137014] [ 9] /camp/apps/misc/stp/sbstp/5.0beta-tomo-GPU/bin/relion_refine_mpi[0x44e65e]
[gpu005:137014] *** End of error message ***
in: /camp/apps/misc/stp/sbstp/relion-5.0/src/acc/cuda/custom_allocator.cuh, line 539
ERROR: 

You ran out of memory on the GPU(s).

Each MPI-rank running on a GPU increases the use of GPU-memory. Relion
tries to distribute load over multiple GPUs to increase performance,
but doing this in a general and memory-efficient way is difficult.

1. Check the device-mapping presented at the beginning of each run,
   and be particularly wary of 'device X is split between N followers', which 
   will result in a higher memory cost on GPU X. In classifications, GPU-
   sharing between MPI-ranks is typically fine, whereas it will usually 
   cause out-of-memory during the last iteration of high-resolution refinement.

2. If you are not GPU-sharing across MPI-follower ranks, then you might be using a
   too-big box-size for the GPU memory. Currently, N-pixel particle images
   will require *roughly* 

		    (1.1e-8)*(N*2)^3  GB  

   of memory (per rank) during the final iteration of refinement (using
   single-precision GPU code, which is default). 450-pixel images can therefore
   just about fit into a GPU with 8GB of memory, since 11*(450*2)^3 ~= 8.02
   During classifications, resolution is typically lower and N is suitably
   reduced, which means that memory use is much lower.

3. If the above estimation fits onto (all of) your GPU(s), you may have 
   a very large number of orientations which are found as possible during
   the expectation step, which results in large arrays being needed on the 
   GPU. If this is the case, you should find large (>10'000) values of 
   '_rlnNrOfSignificantSamples' in your _data.star output files. You can try
   adding the --maxsig <P>, flag, where P is an integer limit, but you 
   should probably also consult expertise or re-evaluate your data and/or 
   input reference. Seeing large such values means relion is finding nothing
   to align.
If none of the above applies, please report the error to the relion
developers at github.com/3dem/relion/issues.

[gpu005:137015] *** Process received signal ***
[gpu005:137015] Signal: Segmentation fault (11)
[gpu005:137015] Signal code: Address not mapped (1)
[gpu005:137015] Failing at address: 0x28
[gpu005:137015] [ 0] /lib64/libpthread.so.0(+0xf630)[0x7f9b3d0f2630]
[gpu005:137015] [ 1] /camp/apps/misc/stp/sbstp/5.0beta-tomo-GPU/bin/relion_refine_mpi(_ZN6AccPtrI8tComplexIdEE9freeIfSetEv+0x48)[0x4bb998]
[gpu005:137015] [ 2] /camp/apps/misc/stp/sbstp/5.0beta-tomo-GPU/bin/relion_refine_mpi(_ZN9Projector26computeFourierTransformMapER13MultidimArrayIdES2_iibbiPKS1_b+0x333e)[0x4ba3ce]
[gpu005:137015] [ 3] /camp/apps/misc/stp/sbstp/5.0beta-tomo-GPU/bin/relion_refine_mpi(_ZN7MlModel23setFourierTransformMapsEbidPK13MultidimArrayIdE+0x8e1)[0x6275a1]
[gpu005:137015] [ 4] /camp/apps/misc/stp/sbstp/5.0beta-tomo-GPU/bin/relion_refine_mpi(_ZN11MlOptimiser16expectationSetupEv+0x5a)[0x64591a]
[gpu005:137015] [ 5] /camp/apps/misc/stp/sbstp/5.0beta-tomo-GPU/bin/relion_refine_mpi(_ZN14MlOptimiserMpi11expectationEv+0x2fb)[0x47fdeb]
[gpu005:137015] [ 6] /camp/apps/misc/stp/sbstp/5.0beta-tomo-GPU/bin/relion_refine_mpi(_ZN14MlOptimiserMpi7iterateEv+0x105)[0x491d25]
[gpu005:137015] [ 7] /camp/apps/misc/stp/sbstp/5.0beta-tomo-GPU/bin/relion_refine_mpi(main+0x54)[0x44b014]
[gpu005:137015] [ 8] /lib64/libc.so.6(__libc_start_main+0xf5)[0x7f9b3c5ee555]
[gpu005:137015] [ 9] /camp/apps/misc/stp/sbstp/5.0beta-tomo-GPU/bin/relion_refine_mpi[0x44e65e]
[gpu005:137015] *** End of error message ***
in: /camp/apps/misc/stp/sbstp/relion-5.0/src/acc/cuda/custom_allocator.cuh, line 539
ERROR: 

You ran out of memory on the GPU(s).

Each MPI-rank running on a GPU increases the use of GPU-memory. Relion
tries to distribute load over multiple GPUs to increase performance,
but doing this in a general and memory-efficient way is difficult.

1. Check the device-mapping presented at the beginning of each run,
   and be particularly wary of 'device X is split between N followers', which 
   will result in a higher memory cost on GPU X. In classifications, GPU-
   sharing between MPI-ranks is typically fine, whereas it will usually 
   cause out-of-memory during the last iteration of high-resolution refinement.

2. If you are not GPU-sharing across MPI-follower ranks, then you might be using a
   too-big box-size for the GPU memory. Currently, N-pixel particle images
   will require *roughly* 

		    (1.1e-8)*(N*2)^3  GB  

   of memory (per rank) during the final iteration of refinement (using
   single-precision GPU code, which is default). 450-pixel images can therefore
   just about fit into a GPU with 8GB of memory, since 11*(450*2)^3 ~= 8.02
   During classifications, resolution is typically lower and N is suitably
   reduced, which means that memory use is much lower.

3. If the above estimation fits onto (all of) your GPU(s), you may have 
   a very large number of orientations which are found as possible during
   the expectation step, which results in large arrays being needed on the 
   GPU. If this is the case, you should find large (>10'000) values of 
   '_rlnNrOfSignificantSamples' in your _data.star output files. You can try
   adding the --maxsig <P>, flag, where P is an integer limit, but you 
   should probably also consult expertise or re-evaluate your data and/or 
   input reference. Seeing large such values means relion is finding nothing
   to align.
If none of the above applies, please report the error to the relion
developers at github.com/3dem/relion/issues.

in: /camp/apps/misc/stp/sbstp/relion-5.0/src/acc/cuda/custom_allocator.cuh, line 539
ERROR: 

You ran out of memory on the GPU(s).

Each MPI-rank running on a GPU increases the use of GPU-memory. Relion
tries to distribute load over multiple GPUs to increase performance,
but doing this in a general and memory-efficient way is difficult.

1. Check the device-mapping presented at the beginning of each run,
   and be particularly wary of 'device X is split between N followers', which 
   will result in a higher memory cost on GPU X. In classifications, GPU-
   sharing between MPI-ranks is typically fine, whereas it will usually 
   cause out-of-memory during the last iteration of high-resolution refinement.

2. If you are not GPU-sharing across MPI-follower ranks, then you might be using a
   too-big box-size for the GPU memory. Currently, N-pixel particle images
   will require *roughly* 

		    (1.1e-8)*(N*2)^3  GB  

   of memory (per rank) during the final iteration of refinement (using
   single-precision GPU code, which is default). 450-pixel images can therefore
   just about fit into a GPU with 8GB of memory, since 11*(450*2)^3 ~= 8.02
   During classifications, resolution is typically lower and N is suitably
   reduced, which means that memory use is much lower.

3. If the above estimation fits onto (all of) your GPU(s), you may have 
   a very large number of orientations which are found as possible during
   the expectation step, which results in large arrays being needed on the 
   GPU. If this is the case, you should find large (>10'000) values of 
   '_rlnNrOfSignificantSamples' in your _data.star output files. You can try
   adding the --maxsig <P>, flag, where P is an integer limit, but you 
   should probably also consult expertise or re-evaluate your data and/or 
   input reference. Seeing large such values means relion is finding nothing
   to align.
If none of the above applies, please report the error to the relion
developers at github.com/3dem/relion/issues.

[gpu005:137016] *** Process received signal ***
[gpu005:137016] Signal: Segmentation fault (11)
[gpu005:137016] Signal code: Address not mapped (1)
[gpu005:137016] Failing at address: 0x28
[gpu005:137013] *** Process received signal ***
[gpu005:137013] Signal: Segmentation fault (11)
[gpu005:137013] Signal code: Address not mapped (1)
[gpu005:137013] Failing at address: 0x28
[gpu005:137016] [ 0] /lib64/libpthread.so.0(+0xf630)[0x7f000170a630]
[gpu005:137016] [ 1] /camp/apps/misc/stp/sbstp/5.0beta-tomo-GPU/bin/relion_refine_mpi(_ZN6AccPtrI8tComplexIdEE9freeIfSetEv+0x48)[0x4bb998]
[gpu005:137016] [ 2] /camp/apps/misc/stp/sbstp/5.0beta-tomo-GPU/bin/relion_refine_mpi(_ZN9Projector26computeFourierTransformMapER13MultidimArrayIdES2_iibbiPKS1_b+0x333e)[0x4ba3ce]
[gpu005:137016] [ 3] /camp/apps/misc/stp/sbstp/5.0beta-tomo-GPU/bin/relion_refine_mpi(_ZN7MlModel23setFourierTransformMapsEbidPK13MultidimArrayIdE+0x8e1)[0x6275a1]
[gpu005:137016] [ 4] /camp/apps/misc/stp/sbstp/5.0beta-tomo-GPU/bin/relion_refine_mpi(_ZN11MlOptimiser16expectationSetupEv+0x5a)[0x64591a]
[gpu005:137016] [ 5] /camp/apps/misc/stp/sbstp/5.0beta-tomo-GPU/bin/relion_refine_mpi(_ZN14MlOptimiserMpi11expectationEv+0x2fb)[0x47fdeb]
[gpu005:137016] [ 6] /camp/apps/misc/stp/sbstp/5.0beta-tomo-GPU/bin/relion_refine_mpi(_ZN14MlOptimiserMpi7iterateEv+0x105)[0x491d25]
[gpu005:137016] [ 7] /camp/apps/misc/stp/sbstp/5.0beta-tomo-GPU/bin/relion_refine_mpi(main+0x54)[0x44b014]
[gpu005:137016] [ 8] /lib64/libc.so.6(__libc_start_main+0xf5)[0x7f0000c06555]
[gpu005:137016] [ 9] /camp/apps/misc/stp/sbstp/5.0beta-tomo-GPU/bin/relion_refine_mpi[0x44e65e]
[gpu005:137016] *** End of error message ***
[gpu005:137013] [ 0] /lib64/libpthread.so.0(+0xf630)[0x7f68cf2a3630]
[gpu005:137013] [ 1] /camp/apps/misc/stp/sbstp/5.0beta-tomo-GPU/bin/relion_refine_mpi(_ZN6AccPtrI8tComplexIdEE9freeIfSetEv+0x48)[0x4bb998]
[gpu005:137013] [ 2] /camp/apps/misc/stp/sbstp/5.0beta-tomo-GPU/bin/relion_refine_mpi(_ZN9Projector26computeFourierTransformMapER13MultidimArrayIdES2_iibbiPKS1_b+0x333e)[0x4ba3ce]
[gpu005:137013] [ 3] /camp/apps/misc/stp/sbstp/5.0beta-tomo-GPU/bin/relion_refine_mpi(_ZN7MlModel23setFourierTransformMapsEbidPK13MultidimArrayIdE+0x8e1)[0x6275a1]
[gpu005:137013] [ 4] /camp/apps/misc/stp/sbstp/5.0beta-tomo-GPU/bin/relion_refine_mpi(_ZN11MlOptimiser16expectationSetupEv+0x5a)[0x64591a]
[gpu005:137013] [ 5] /camp/apps/misc/stp/sbstp/5.0beta-tomo-GPU/bin/relion_refine_mpi(_ZN14MlOptimiserMpi11expectationEv+0x2fb)[0x47fdeb]
[gpu005:137013] [ 6] /camp/apps/misc/stp/sbstp/5.0beta-tomo-GPU/bin/relion_refine_mpi(_ZN14MlOptimiserMpi7iterateEv+0x105)[0x491d25]
[gpu005:137013] [ 7] /camp/apps/misc/stp/sbstp/5.0beta-tomo-GPU/bin/relion_refine_mpi(main+0x54)[0x44b014]
[gpu005:137013] [ 8] /lib64/libc.so.6(__libc_start_main+0xf5)[0x7f68ce79f555]
[gpu005:137013] [ 9] /camp/apps/misc/stp/sbstp/5.0beta-tomo-GPU/bin/relion_refine_mpi[0x44e65e]
[gpu005:137013] *** End of error message ***
srun: error: gpu005: tasks 2-4: Segmentation fault
srun: error: gpu005: task 1: Segmentation fault
srun: Job step aborted: Waiting up to 32 seconds for job step to finish.
slurmstepd: error: *** JOB 63128037 ON gpu005 CANCELLED AT 2023-12-31T17:13:26 ***
slurmstepd: error: *** STEP 63128037.0 ON gpu005 CANCELLED AT 2023-12-31T17:13:26 *****

```
A line in the STAR file contains fewer columns than the number of labels. Expected = 3 Found = 2
Error in line: 0 0.0
in: /prog/relion-devel-lmb/src/metadata_table.cpp, line 966
=== Backtrace  ===
/prog/relion-devel-lmb/bin/relion_motion_refine_mpi(_ZN11RelionErrorC1ERKSsS1_l+0x41) [0x42e981]
/prog/relion-devel-lmb/bin/relion_motion_refine_mpi(_ZN13MetaDataTable12readStarLoopERSt14basic_ifstreamIcSt11char_traitsIcEEPSt6vectorI8EMDLabelSaIS6_EESsb+0xedd) [0x4361ad]
/prog/relion-devel-lmb/bin/relion_motion_refine_mpi(_ZN13MetaDataTable8readStarERSt14basic_ifstreamIcSt11char_traitsIcEERKSsPSt6vectorI8EMDLabelSaIS8_EESsb+0x580) [0x436f10]
/prog/relion-devel-lmb/bin/relion_motion_refine_mpi(_ZN10Micrograph4readE8FileNameb+0x5a3) [0x454bb3]
/prog/relion-devel-lmb/bin/relion_motion_refine_mpi(_ZN10MicrographC2E8FileNameS0_d+0x2e3) [0x4568b3]
/prog/relion-devel-lmb/bin/relion_motion_refine_mpi(_ZN17MicrographHandler14isMoviePresentERK13MetaDataTableb+0x180) [0x568280]
/prog/relion-devel-lmb/bin/relion_motion_refine_mpi(_ZN17MicrographHandler17cullMissingMoviesERKSt6vectorI13MetaDataTableSaIS1_EEi+0xe6) [0x568dc6]
/prog/relion-devel-lmb/bin/relion_motion_refine_mpi(_ZN13MotionRefiner4initEv+0x56f) [0x49e1ff]
/prog/relion-devel-lmb/bin/relion_motion_refine_mpi(main+0x31) [0x42a5e1]
/lib64/libc.so.6(__libc_start_main+0xf5) [0x2b7ac026e495]
/prog/relion-devel-lmb/bin/relion_motion_refine_mpi() [0x42b3cf]
==================
```

**Comment by pherepanov** [comment]
An update on this issue: the GPU memory errors arise when refining binned subtomograms. Refining unbinned subtomograms works fine. However, binned subtomograms can be refined with an earlier version of relion (I use 4.0beta, commit a26bd4) in the same project directory.

**Comment by pherepanov** [comment]
Final update: the bug was affecting relion_refine when box was <44 pixels. So if someone is having a smilar issue with relion-5.0beta re-extract your subtomos with a larger box.

**Comment by oleuns** [comment]
Hey,

I am encountering similar issues, as described the exact same errors sometimes occur at a random interaction during 3D classification or 3D refinement. The dataset contains 37,000 particles with a box size of 256, 3 MPIs for 3D refinement, and 1 MPI for 3D classification. I tested this on an RTX3080 TI (11 GB VRAM) and Quadro RTX5000 (16 GB VRAM). I rerun the 3D classifications/3D refinements multiple times until the job finished, I could not identify a particular pattern.

**Comment by pherepanov** [comment]
Just to clarify: the issue with subtomo refinements I was experincing has been solved in the current beta release (thank you Sjors!).

**Comment by oleuns** [comment]
I am currently running RELION version: 5.0-beta-0-commit-90d239  (I hope this is the current beta release) and still encountered these issues in 3D classification and 3D auto refinement. However, this was SPA processing and not using subtomograms (sorry I forgot to mention this).

**Comment by biochem-fan** [comment]
@oleuns are you sure you replied to the right thread? Did you mean https://github.com/3dem/relion/issues/1061?

**Comment by oleuns** [comment]
@biochem-fan maybe I should open a new thread describing the issue that I encountered, the error message was just identical to the one described in #1061.
