### ISSUE TITLE
Relion5.0  tomo

### ISSUE THREAD

**Issue by nbcronin** [3dem/relion#1087]
Installed Relion5.0.     with no problem.  Runs with programs in the environment.yml (relion_blush; topaz etc)

Currently want to run relion --tomo ( Relion-5.0-beta-1-commit-b75b38) and get the error

---------------------------------- PYTHON ERROR ---------------------------------
   Has RELION been provided a Python interpreter with the correct environment?
   The interpreter can be passed to RELION either during Cmake configuration by
     using the Cmake flag -DPYTHON_EXE_PATH=<path/to/python/interpreter>.
---------------------------------------------------------------------------------

  Using python executable: /opt/anaconda3/envs/relion-5.0/bin/python

ModuleNotFoundError: No module named 'tomography_python_programs'

The path for the python executable is correct - is there a module named tomography_python_programs?

Thanks

Nora

**Comment by nbcronin** [comment]
I can see the tomo programs are located - in a relion/src/tomography_python_programs - ie there an environment variable to point to this?  Currently it is looking at the conda environment to locate the programs.

nora

**Comment by LIjieHan** [comment]
I'm having the same problem, did you figure out how to fix it?

**Comment by nbcronin** [comment]
Hi

Yes the problem has been resolved.   The advice I received is very simple:

"Before running cmake, you
must have conda in your path (but not activated relion-5.0 env). Cmake
will create Python files inside the bin directory."

Once you have created the environment place the path
in your profile.d (or local equivalent)  eg a python.sh file:

export PATH=/opt/anaconda3/envs/relion-5.0/bin/:$PATH

 ie wherever your path to the relion-5.0 environment is located.

Then run cmake etc

The difference between correct and incorrect is that you will now see the tomo executables in the conda bin area above.

Best

Nora


Nora Cronin
LonCEM Facility Manager

The Francis Crick Institute

1 Midland Road

London NW1 1AT


T: +442037965225

E: ***@***.******@***.***>

W: www.crick.ac.uk<http://www.crick.ac.uk/>

________________________________

**Comment by Qiangong2** [comment]
The files are successfully made in the bin directory, but we still get the python error.

**Comment by nbcronin** [comment]
Hi

You are attempting to use Dynamight ?   Do you see it in the conda path (/opt/anaconda3/envs/relion-5.0/bin - this is my one):

-rwxr-xr-x. 1 croninn  256 Mar 19 15:08 relion_tomo_denoise
-rwxr-xr-x. 1 croninn  266 Mar 19 15:08 relion_tomo_align_tilt_series
-rwxr-xr-x. 1 croninn  253 Mar 19 15:08 relion_tomo_view
-rwxr-xr-x. 1 croninn  253 Mar 19 15:08 relion_tomo_pick
-rwxr-xr-x. 1 croninn  267 Mar 19 15:08 relion_tomo_import
-rwxr-xr-x. 1 croninn  267 Mar 19 15:08 relion_tomo_get_particle_poses
-rwxr-xr-x. 1 croninn  268 Mar 19 15:08 relion_tomo_exclude_tilt_images
-rwxr-xr-x. 1 croninn  231 Mar 19 15:08 dynamight

Try running from the cmd line:

relion_python_dynamight --help

(base) ***@***.*** Jie]$ relion_python_dynamight --help

 Usage: -c [OPTIONS] COMMAND [ARGS]...

╭─ Options ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ --help          Show this message and exit.                                                                                                                               │
╰───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─ Commands ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ compute-masks-for-rigid-transforms                                                                                                                                        │
│ compute-rigid-transforms                                                                                                                                                  │
│ deformable-backprojection                                                                                                                                                 │
│ deformable-backprojection-correction                                                                                                                                      │
│ deformable-backprojection-single                                                                                                                                          │
│ deformable-backprojection-single-deformation                                                                                                                              │
│ explore-latent-space                                                                                                                                                      │
│ optimize-deformations                                                                                                                                                     │
│ optimize-deformations-rigid                                                                                                                                               │
│ optimize-deformations-single                                                                                                                                              │
│ optimize-inverse-deformations                                                                                                                                             │
│ optimize-inverse-deformations-single                                                                                                                                      │
╰─

The python error indicates that the program is not correctly installed?

Best

Nora



Nora Cronin
LonCEM Facility Manager

The Francis Crick Institute

1 Midland Road

London NW1 1AT


T: +442037965225

E: ***@***.******@***.***>

W: www.crick.ac.uk<http://www.crick.ac.uk/>

________________________________

**Comment by Qiangong2** [comment]
Hi @nbcronin, No, dynamight is functional, but the other tomo python programs do not. The conda paths are fine, Relion is able to find the correct python path during compilation and any other tools except for the tomo tools.

**Comment by Qiangong2** [comment]
@biochem-fan Any ideas?

**Comment by EricDeveaud** [comment]
hello, 
had the same problem with relion-5.0 and found that among this python module some other are missing,
I fixed it by.

```
    # used by relion_python_tomo_align_tilt_series
    cd $(SOFT)/src && cp -r tomography_python_programs $(PYLIB)
    $(PIP) install makefun yet_another_imod_wrapper lil_aretomo
    # used by relion_python_tomo_get_particle_poses
    $(PIP) install morphosamplers
    # used by relion_python_tomo_pick
    $(PIP) install napari_threedee
    # used by relion_python_tomo_pick relion_python_tomo_view relion_python_tomo_exclude_tilt_images
    $(PIP) install lru-dict
```

NB installation performed out of conda.

**Comment by nbcronin** [comment]
Hi

I found the solution to this problem entails installing in the correct order.    Starting from scratch - new relion install  and  conda environment not installed; before creating the conda environment, create the 'build' subdirectory.   Then create the conda environment running the environment.yml file from the ~/relion repository - you will see the 'tomography_python_programs' directory  appearing in the build 'lib' subdirectory:

cd /home/supervisor/relion-5.0/relion/build/lib

drwxr-xr-x.  6 supervisor 4.0K Apr 10 14:49 acc/
drwxr-xr-x.  2 supervisor 4.0K Apr 10 14:49 apps/
drwxr-xr-x.  3 supervisor 4.0K Apr 10 14:49 Eigen/
drwxr-xr-x. 19 supervisor 4.0K Apr 10 14:49 jaz/
drwxr-xr-x.  2 supervisor  143 Apr 10 14:49 lbfgs/
-rw-r--r--.  1 root       6.8M Apr 10 17:09 librelion_gpu_util.a
-rw-r--r--.  1 root       2.3M Apr 10 17:05 librelion_gui_lib.a
-rw-r--r--.  1 root        14K Apr 10 17:09 librelion_jaz_gpu_util.a
-rw-r--r--.  1 root        39M Apr 10 17:05 librelion_lib.a
drwxr-xr-x.  2 supervisor  116 Apr 10 14:49 spherical-harmonics/
drwxr-xr-x. 13 supervisor 4.0K Apr 10 14:49 tomography_python_programs/


Then proceed with cmake etc. with the conda python environment in the path (but not activated).

Best

Nora



Nora Cronin
LonCEM Facility Manager

The Francis Crick Institute

1 Midland Road

London NW1 1AT


T: +442037965225

E: ***@***.******@***.***>

W: www.crick.ac.uk<http://www.crick.ac.uk/>

________________________________

**Comment by Qiangong2** [comment]
Hi @nbcronin

Unfortunately, it still doesn't work.

```
---------------------------------- PYTHON ERROR ---------------------------------
   Has RELION been provided a Python interpreter with the correct environment?
   The interpreter can be passed to RELION either during Cmake configuration by
     using the Cmake flag -DPYTHON_EXE_PATH=<path/to/python/interpreter>.
---------------------------------------------------------------------------------
```
The above error appears specifically on `relion_python_tomo_import`, `relion_python_tomo_denoise`, `relion_python_tomo_exclude_tilt_images`, `relion_python_modelangelo`, `relion_python_topaz`, and `relion_python_tomo_align_tilt_series`. The other python tools are fine.

@biochem-fan Can you please provide an update on this?

**Comment by biochem-fan** [comment]
@Qiangong2 I am not involved in the tomography aspect of RELION, so I cannot help.

**Comment by Qiangong2** [comment]
> @Qiangong2 I am not involved in the tomography aspect of RELION, so I cannot help.

@biochem-fan Who is then?
