### ISSUE TITLE
DynaMight missing python modul

### ISSUE THREAD

**Issue by Poko18** [3dem/relion#1092]
**Problem**
Since last week, we had problems with running dynamight with relion 5.0. Error we get seems to be related to dynamight code installed with relion5. Has anyone experienced similar problem?

**Job options:**
   ```
relion_python_dynamight optimize-deformations --refinement-star-file Refine3D/run_it016_data.star --output-directory DynaMight/ --initial-model Refine3D/run_it016_half1_class001.mrc --initial-resolution 8 --n-gaussians 30000 --n-gaussian-widths 1 --n-latent-dimensions 5 --n-positional-encoding-dimensions 10 --n-linear-layers 8 --n-neurons-per-layer 32 --n-warmup-epochs 10 --consensus-update-rate 1.0 --consensus-update-pooled-particles 500 --regularization-factor 0.9 --particle-diameter 280.0 --soft-edge-width 20.0 --batch-size 256 --n-epochs 150 --n-threads 8 --n-workers 32 --combine-resolution 8.0 --use-data-normalization --kld-factor 0.01
   ```

**Error message:**
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/conda/envs/relion-5.0/lib/python3.10/site-packages/dynamight/__init__.py", line 3, in <module>
    from .deformations import optimize_deformations, optimize_deformations_rigid
  File "/opt/conda/envs/relion-5.0/lib/python3.10/site-packages/dynamight/deformations/__init__.py", line 3, in <module>
    from. optimize_deformations_rigid import optimize_deformations_rigid
ModuleNotFoundError: No module named 'dynamight.deformations.optimize_deformations_rigid'
---------------------------------- PYTHON ERROR ---------------------------------
   Has RELION been provided a Python interpreter with the correct environment?
   The interpreter can be passed to RELION either during Cmake configuration by
     using the Cmake flag -DPYTHON_EXE_PATH=<path/to/python/interpreter>.
---------------------------------------------------------------------------------
  Using python executable: /opt/conda/envs/relion-5.0/bin/python
```

**Comment by Qiangong2** [comment]
@biochem-fan Having the exact same issue. Occurs even after removing and rebuilding. We're using Ubuntu 22.04.

**Comment by biochem-fan** [comment]
@schwabjohannes @dkimanius
Did you change something?

**Comment by Poko18** [comment]
We also tried to rebuild RELION and it did not work.
Seems like `dynamight.deformations.optimize_deformations_rigid` module is missing, which was added recently: https://github.com/3dem/DynaMight/commit/5760613f094e17c768b6f0eec81bccfbca9cc569

**Comment by schwabjohannes** [comment]
I think it was a typo, should be fixed now.

**Comment by Poko18** [comment]
changes fixed the issue, thanks!

**Comment by Qiangong2** [comment]
@biochem-fan While dynamight is now working, we're still receiving the Python interpreter error on the python tomo tools.

**Comment by biochem-fan** [comment]
@Qiangong2 Let's discuss tomography issues on #1087.
